# Generated by Django 3.2.18 on 2023-03-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230306_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='the_question',
            new_name='question',
        ),
    ]
