# Generated by Django 3.1.3 on 2023-03-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20230307_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_grade',
            field=models.FloatField(default=80),
        ),
    ]
